baseURL: "https://soheil-mech.github.io/" 
title: Soheïl Mecheloukh
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "Ce site contient les informations de Soheïl Mecheloukh, étudiant en M2 de Statistique et Sciences des données."
    author: Soheïl Mecheloukh
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Soheïl Mecheloukh
          subtitle: "Je suis étudiant en M2 de Statistique et Sciences des données."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projet tutoré  de M1
              url: ProjetM1/
            - name: Stage de M1
              url: StageM1/
            - name: Projet tutoré de M2
              url: ProjetM2/
            - name: Stage de M2
              url: StageM2/
            - name: Tags
              url: 
            - name: Archive
              url: 
            - name: Blog
              url: 

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:soheil.mecheloukh@orange.fr
        - name: Zoom
          url: 
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: 
        - name: GitHub
          url: https://github.com/soheil-mech
        - name: Substack
          url: 
        - name: YouTube
          url: 
        - name: Twitter
          url: 
        - name: Bluesky
          url: 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Soheïl Mecheloukh"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2